### ISSUE TITLE
Can't get to work on UNO (nano)

### ISSUE THREAD

**Issue by nonix** [dualB/Musician#1]
Hi I have compiled / uploaded your demo sketch to Arduino Nano, but it won't play. (did try Melody as well as Musician).
The Musician does not even initialize, I've added serial.print as last step in setup(), but the code does not reach that line.
Otherwise interesting project
Thx,
 N.

**Comment by dualB** [comment]
Thanks you for your interest in the project! I haven't tested it yet on Nano, or UNO, I will grab one at work in the next days to be able to test it and propose some changes.

**Comment by dualB** [comment]
Hello, I made it work on a NANO, it is mainly a memory problem : my examples files were too ambitious for the capacity of the device.
Could you please check this new example file ? 
[example_with_memory_limited_devices](https://github.com/dualB/Musician/tree/master/examples/example_with_memory_limited_devices) 
Thank you!

**Comment by nonix** [comment]
Hello Claude, Yes I can confirm to work well on Nano. Well done!
Thank you,
 N.
