### ISSUE TITLE
playSync() issues the Soft WDT reset

### ISSUE THREAD

**Issue by qwertyLabGmbH** [dualB/Musician#2]
ESP8266
Arduino Studio 1.8.13
When running Musician_in_sync.ino from examples it crashes with the message:
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffda0 end: 3fffffc0 offset: 01a0
3fffff40:  00000000 00000000 00000004 40204624  
3fffff50:  000ebd56 0000014a 3ffee568 40201170  
3fffff60:  00000bff 00000001 3ffee568 3ffee644  
3fffff70:  3fffdad0 00000000 3ffee568 40201c14  
3fffff80:  3fffdad0 00000000 3ffee568 40201cda  
3fffff90:  3fffdad0 00000000 3ffee5d8 4020106c  
3fffffa0:  feefeffe feefeffe 3ffee604 402026e8  
3fffffb0:  feefeffe feefeffe 3ffe84e0 40100ec9  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

**Comment by dualB** [comment]
Hello, I have a few questions for you:
 - Have you tried others examples file? Does it crash too?
 - Have you tried to change the melody (a shorter one) in Musician_in_sync example?
 - Could you try to remove everthing unnecessary in the example (Serial, println, delay) and keep only " musician.playSync(); ", does it work? 
 - What is your specific hardware you are using?
 
Thank you!

**Comment by dualB** [comment]
I have read somewhere that using a routine that block the loop() for a certain time can trigger the Watchdog Reset.
Maybe the solution in that case (when there is a WDT) is to NOT use a blocking method, like "playSync()".

**Comment by dualB** [comment]
No news is good news, I suppose.
